
export const EXCHANGES_LOADING = 'EXCHANGES_LOADING';
export const EXCHANGES_FAILED = 'EXCHANGES_FAILED';
export const ADD_EXCHANGES = 'ADD_EXCHANGES';
export const LENDERS_LOADING = 'LENDERS_LOADING';

export const LENDERS_FAILED = 'LENDERS_FAILED';
export const SWAPPOOLS_LOADING = 'SWAPPOOLS_LOADING';
export const SWAPPOOLS_FAILED = 'SWAPPOOLS_FAILED';
export const ADD_SWAPPOOLS = 'ADD_SWAPPOOLS';
export const LENDERPOOLS_LOADING = 'LENDERPOOLS_LOADING';
export const LENDERPOOLS_FAILED = 'LENDERPOOLS_FAILED';
export const ADD_LENDERPOOLS = 'ADD_LENDERPOOLS';

export const OPERATION_ADD = 'OPERATION_ADD';
export const OPERATION_CLEAR = 'OPERATION_CLEAR';
export const OPERATION_EXECUTE = 'OPERATION_EXECUTE';
export const OPERATION_INIT = 'OPERATION_INIT';