
export const EXCHANGES_LOADING = 'EXCHANGES_LOADING';
export const EXCHANGES_FAILED = 'EXCHANGES_FAILED';
export const ADD_EXCHANGES = 'ADD_EXCHANGES';
/*export const LENDERS_LOADING = 'LENDERS_LOADING';
export const ADD_LENDERS = 'ADD_LENDERS';
export const LENDERS_FAILED = 'LENDERS_FAILED';*/
export const SWAPPOOLS_LOADING = 'SWAPPOOLS_LOADING';
export const SWAPPOOLS_FAILED = 'SWAPPOOLS_FAILED';
export const ADD_SWAPPOOLS = 'ADD_SWAPPOOLS';
